import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Forte Edges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box color="brand.body_text">Welomce here</Box>

        <Box
          width="100px"
          h="100px"
          bgGradient="linear(to-r, #7950DA, #8F6FDB)"
          // bg="black"
        ></Box>
      </main>
    </Box>
  );
}
